### PR TITLE
added ResidentsMap to respective php page

### LINKED ISSUE #29: KS Resident, etc map PR

### PR DESCRIPTION
**Pull request by thekaysev**

### CODE REVIEW

**Comment by thekaysev** [comment]
I added the Residents map to the respective page and submitted a PR to check for any merge conflicts.

**Review by AlphaAndTheOshea — APPROVED** [review]
Bueno!!! Looks good. We definetly need this brought in to main. ¡Perfectamente formateado!

**Review by JMitch55 — APPROVED** [review]
Code looks good. Link works, code is neatly formatted, img src works as well. Approved. We need this brought into the main!

**Review by barrycumbie — COMMENTED** [review]
Here's a review.

1. I click on FILES CHANGED
2. I then click on big GREEN "Start Review" OR I start it by commenting on a specific line of code. 
3. I submit my review!

**Comment by barrycumbie** [comment]
> Code looks good. Link works, code is neatly formatted, img src works as well. Approved. We need this brought into the main!

See my review? Not an PR Comment.

**Pull request closed without merging**
