### PR TITLE
added faculty map to respective file and to /img

### LINKED ISSUE #26: PR for adding faculty map

### PR DESCRIPTION
**Pull request by thekaysev**
Just sent this for double-check in case someone has something out and is working on it

### CODE REVIEW

**Comment by thekaysev** [comment]
https://una-parking-app.herokuapp.com/docs/facultyMap.php
This is the test link for the Faculty Map that I added to the repo

**Comment by AlphaAndTheOshea** [comment]
This looks fine to me! lol. It worked when I tested it! 

This is the test link for Review @barrycumbie
[https://una-parking-app.herokuapp.com/docs/facultyMap.php](https://una-parking-app.herokuapp.com/docs/facultyMap.php)

I deployed on branch iss26 on Heroku
image

The image displays properly!  Great Job Kaylin.
image

**Review by AlphaAndTheOshea — COMMENTED** [review]
This looks fine to me! lol. It worked when I tested it! 

This is the test link for Review @barrycumbie
[https://una-parking-app.herokuapp.com/docs/facultyMap.php](https://una-parking-app.herokuapp.com/docs/facultyMap.php)

I deployed on branch iss26 on Heroku
image

The image displays properly!  Great Job Kaylin.
image

**Review by AlphaAndTheOshea — COMMENTED** [review]
This looks fine to me! lol. It worked when I tested it! 

This is the test link for Review @barrycumbie
[https://una-parking-app.herokuapp.com/docs/facultyMap.php](https://una-parking-app.herokuapp.com/docs/facultyMap.php)

I deployed on branch iss26 on Heroku
image

The image displays properly!  Great Job Kaylin.
image

**Pull request merged**
